import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/ui/navbar";
import { font_rubik, font_raleway } from "@/components/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={font_raleway.className} data-theme="dark">
        <Navbar />
        <section data-theme="dark">{children}</section>
      </body>
    </html>
  );
}
